version: 1
labels:
  - label: feature
    title: ^(?:[fF]eature|[fF]eat):.*
  - label: fix
    title: ^(?:[bB]ugfix|[fF]ix):.*
  - label: feature
    branch: ^(?:[fF]eature|[fF]eat)[-/].*
  - label: fix
    branch: ^(?:[bB]ugfix|[fF]ix)[-/].*
