name: "Lint GitHub Actions"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: reviewdog/action-actionlint@534eb894142bcf31616e5436cbe4214641c58101 # v1.61.0
        with:
          reporter: github-check
          fail_on_error: true
